Baseball
yeeuniii/java-baseball-6 pull request #1
Opened 2023-10-27 09:50 UTC by yeeuniii

코드 리뷰 요청합니다!!

2023-10-27 11:45 UTC, redparkchu requested changes
자바를 처음하는것 같아서 많은 힌트를 리뷰에 작성했는데 작성된 리뷰대로 수정만 하지 말고 '왜 이렇게 하면 좋을까', '이게 정말 좋은걸까' 같은 생각을 하면서 피드백을 반영해주면 좋을것 같아요!

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        boolean retry = true;
해당 사이트를 참고해서 변수명을 수정해주세요.
https://soojin.ro/blog/naming-boolean-variables

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +public class InputNumber {
숫자야구게임에서 컴퓨터가 가지고 있는 숫자와 사용자가 입력한 숫자는 공통점이 많지 않을까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    private List<Integer> numbers;
클래스명은 InputNumber 인데 변수명을 numbers 로 한 이유가 있을까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +        }
사용자가 입력한 값을 Integer 로 변환해도 되지만 다음과 같이 String 을 유지한채로 구현하면 어떨까요?
```Java
Set<Character> numbers = HashSet<>(input.toCharArray())
```

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +        setNumbers(Integer.parseInt(input));
setNumbers 안에서 입력받은 값을 확인해주는건 어떨까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    public InputNumber(String input) {
input 이라는 변수명은 코드를 처음보는 사람이 봤을땐 어떤 역할을 하는지 이해하기 힘들어 보여요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    private List<Integer> numbers;
numbers 에 중복된 값이 올수 없다면 checkInput 에서 했던것처럼 Set 자료구조를 이용해보는건 어떨까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    }
해당 사이트를 참고해서 함수명을 수정해주세요.
https://soojin.ro/blog/naming-boolean-variables

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +        }
numbers collection 이 가지는 모든 element 에 접근하기 위한 for 문 이라면 forEach 문 에 대해 찾아보면 좋을거 같아요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +            return ;
빈 반환값은 좋지 않아요.
result 를 반환하는 식으로 구현하는건 어떨까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    }
화면에 출력하는 기능을 분리해주세요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +    private Type getResultType(int index, Integer number, List<Integer> answer) {
answer 를 클래스로 만들고 getResultType 메소드를 가지게 구현하면 어떨까요?

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +        result += map.get(Type.Strike) > 0 ? map.get(Type.Strike).toString() + "스트라이크" : "";
enum class 를 다음과 같이 활용해 볼 수 있어요.
```Java
enum Type {
    None(""), 
    Ball("볼"), 
    Strike("스트라이크");

    private String name;

    Type(String name) {
        this.name = name;
    }

    public String getResult(Integer time) {
        return time > 0 ? String.format("%d%s", time, this.name) : "";
    }
}

result = Type.Ball.getResult(map.get(Type.Ball));
```

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/InputNumber.java
> +        HashMap<Type, Integer> map = new HashMap<>();
map, set, list, integer, string 등등 이미 java 에서 사용되고 있는 이름으로 변수명을 만드는건 좋지 않아요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +            InputNumber input = new InputNumber(Console.readLine());
화면에서 입출력받는 기능을 분리해주세요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +    }
화면에서 입출력받는 기능을 분리해주세요.

2023-10-27 11:45 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        }
java 의 shuffle 과 subList 를 활용하면 좀더 간결한 코드를 작성할 수 있습니다!

2023-10-29 07:18 UTC, yeeuniii commented on src/main/java/baseball/InputNumber.java
> +        }
천재인 거 같습니다!

2023-10-29 07:19 UTC, yeeuniii commented on src/main/java/baseball/InputNumber.java
> +    private List<Integer> numbers;
천재 ...?!

2023-10-29 09:35 UTC, yeeuniii commented on src/main/java/baseball/InputNumber.java
> +    private List<Integer> numbers;
근데 이 피드백 numbers를 아예 Set 자료구조로 선언하라는 의미일까요?

2023-10-30 14:36 UTC, redparkchu requested changes
클래스가 가지고 있는 속성값을 잘 활용하지 않는거 같아요.
제가 예시로 코드 리펙토링한걸 redparkchu 브랜치에 올려둘게요.
피드백 반영 다하고 본인 코드랑 비교해보세요!

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +    public static final String END = "3스트라이크";
게임이 끝나야 되는 결과를 변수로 만든거 좋아요 👍

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        while (!result.equals(END)) {
result 를 Game class 가 속성으로 가지고 있으면 Game 에게 지금 게임이 진행중인지 물어볼 수 있지 않을까요?

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        while (willRestart) {
restart 해야되는 상황도 결국 게임이 계속되고 있는 상황 아닐까요? 
result 에 대한 처리를 더 생각해보면 while 문을 하나로 줄일수 있을거 같아요!

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Type.java
> +
불필요한 공백은 지워주세요!

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        Numbers computer = new Numbers();
플레이어가 `맞춰야 하는 숫자` 라는 의미를 나타내면 좋을거 같아요.

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +            Numbers user = new Numbers(Screen.inputUserNumber());
플레이어가 `질문하는 숫자` 라는 의미를 나타내면 좋을거 같아요.

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +    }
Numbers 에서 result 를 만들땐 None, Ball, Strike 의 개수만 구하고 해당 result 에 대한 View 함수는 Screen 에서 구현하는게 어떨까요?

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +            throw new IllegalArgumentException("Invalid input");
if 문이나 for 문 뒤에는 {  } 를 넣어주세요

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Screen.java
> +    }
입력 받아온 값이 유효한 값인지 여기서 확인하는게 좋지 않을까요?
아니면 여기서 Numbers 를 생성해 반환하는 방법도 있어요!

2023-10-30 14:36 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +    private Type getResultType(int index, Integer number, Numbers other) {
함수 인자는 2개를 넘기지 않는게 좋아요.

2023-10-30 14:55 UTC, redparkchu commented
> 클래스가 가지고 있는 속성값을 잘 활용하지 않는거 같아요. 제가 예시로 코드 리펙토링한걸 redparkchu 브랜치에 올려둘게요. 피드백 반영 다하고 본인 코드랑 비교해보세요!

2023-10-30 14:56 UTC, redparkchu commented
시간이 부족해서 제가 리팩토링한건 내일 올려야될거 같네요 ㅠㅠ

2023-10-31 10:45 UTC, redparkchu commented on src/main/java/baseball/Game.java
> +        while (willRestart) {
이부분에 대한 리뷰는 정정할게요.
while 문의 특성을 잘 활용한 좋은 코드였어요! 굳이 하나로 줄이지 않아도 될거 같습니다 👍

2023-10-31 10:54 UTC, redparkchu commented
@yeeuniii 
`redparkchu` 브랜치에 yeeuniii 학생이 작성한 코드를 제가 리펙토링해서 올려놨어요.
피드백 반영 다 하고 본인 코드랑 비교해 보면 좋을거 같아요!

2023-10-31 10:54 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +    }
Result 를 클래스로 만드는 방법도 있어요!

2023-10-31 11:04 UTC, redparkchu requested changes
어제 시간이 없어서 리뷰를 제대로 못한거 같아 추가 리뷰 남겨요.
우선 전반적으로 피드백 반영 너무 잘해줬어요. 💯 
특히 화면 출력하는 부분을 잘 나눠준거 같아요 👍 
근데 지금 보면 불필요하게 public 되어 있는 클래스 속성과 메서드들이 많아요.
처음 만들땐 private 으로 만들어두고 나중에 필요하면 public 으로 바꾸는 습관을 들이면 좋을거 같아요!

2023-10-31 11:04 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +    private LinkedHashSet<Integer> content;
그냥 List 를 쓰는게 더 편한거 같네요.
잘못된 피드백으로 혼란을 줘서 죄송해요 😭

2023-10-31 11:04 UTC, redparkchu commented on src/main/java/baseball/Numbers.java
> +        return Type.None;
Strike, Ball, None 을 구하는 알고리즘을 잘 구현해서 이중 for문을 돌지 않게 구현한거 좋아요 👍

2023-11-03 16:47 UTC, yeeuniii commented on src/main/java/baseball/Screen.java
> +    }
왜 여기서 확인하는게 좋은가요??
만약 단위테스트를 작성한다면, 여기서 numbers의 유효성을 확인하게 될 경우 단위테스트 확인이 어려워지지 않나요?

2023-11-03 17:54 UTC, yeeuniii commented
역시 스승님은 대단하시군요.. 코드보고 박수를 쳤습니다.. Result를 통해서 훨씬 객체지향적으로 바뀐것 같아요!!
그리고 숫자의 유효성 확인하는 부분도 굉장히 신선한 방법이었습니다!! 나올 값들이 정해져있으니까 그 안에서 랜덤을 뽑는 것도.. 존경스럽습니다!
잘 기억하고 나중에 사용하도록 하겠습니다!

2023-11-05 12:48 UTC, redparkchu commented
@yeeuniii 
로또 PR 보내 
8282

2023-11-05 13:04 UTC, redparkchu commented on src/main/java/baseball/Screen.java
> +    }
좋은 지적이에요!
단위 테스트를 만들게 되면 private 한 함수는 테스트 하기 어렵죠 😅 
Numbers 에서 생성할때 유효성 검사 하는 방법이 더 좋은 방법인거 같네요! 😄

2023-11-05 13:07 UTC, redparkchu approved these changes
피드백 반영 잘했네요 💯 
처음 객체지향적으로 구현할려 해서 많이 힘들었을텐데 그래도 클래스 잘 구현하고 전체적인 틀을 잘 잡는거 같아요 👍
다음 과제에선 테스트 코드도 기대할게요!

2023-11-05 14:44 UTC, merged